-- Migration: Create tables for AI-powered features
-- AI Focus Coach, Distraction Detector, Time Predictions, Smart Suggestions

-- Tasks table for AI Focus Coach
CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'pending', -- pending, in_progress, completed, cancelled
    priority VARCHAR(16) DEFAULT 'medium', -- low, medium, high, urgent
    estimated_minutes INTEGER,
    actual_minutes INTEGER,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    completed_at TIMESTAMP,
    due_date TIMESTAMP,
    tags TEXT[] DEFAULT '{}',
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Activity patterns for AI Distraction Detector
CREATE TABLE IF NOT EXISTS activity_patterns (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    activity_type VARCHAR(64) NOT NULL, -- message_received, app_switch, website_visit, etc.
    activity_category VARCHAR(64) NOT NULL, -- communication, entertainment, work, etc.
    timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
    duration_seconds INTEGER DEFAULT 0,
    context JSONB DEFAULT '{}'::jsonb,
    distraction_score DECIMAL(3, 2) DEFAULT 0.0, -- 0.0 to 1.0
    created_at TIMESTAMP DEFAULT NOW()
);

-- AI Time Predictions
CREATE TABLE IF NOT EXISTS time_predictions (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    task_id INTEGER REFERENCES tasks(id) ON DELETE CASCADE,
    predicted_minutes INTEGER NOT NULL,
    confidence_score DECIMAL(3, 2) DEFAULT 0.0, -- 0.0 to 1.0
    model_version VARCHAR(32),
    input_features JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP DEFAULT NOW(),
    actual_minutes INTEGER,
    accuracy_score DECIMAL(3, 2), -- calculated after task completion
    validated_at TIMESTAMP
);

-- AI Focus Plans (generated by AI Focus Coach)
CREATE TABLE IF NOT EXISTS focus_plans (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    plan_type VARCHAR(32) NOT NULL, -- daily, weekly, session
    title VARCHAR(255) NOT NULL,
    description TEXT,
    tasks_summary JSONB DEFAULT '[]'::jsonb, -- Array of task summaries
    recommended_schedule JSONB DEFAULT '{}'::jsonb, -- Time slots and task assignments
    focus_strategy TEXT, -- AI-generated strategy
    estimated_total_minutes INTEGER,
    status VARCHAR(32) DEFAULT 'draft', -- draft, active, completed, archived
    created_at TIMESTAMP DEFAULT NOW(),
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Focus plan tasks mapping
CREATE TABLE IF NOT EXISTS focus_plan_tasks (
    id SERIAL PRIMARY KEY,
    focus_plan_id INTEGER REFERENCES focus_plans(id) ON DELETE CASCADE,
    task_id INTEGER REFERENCES tasks(id) ON DELETE CASCADE,
    scheduled_order INTEGER NOT NULL,
    scheduled_time TIMESTAMP,
    estimated_minutes INTEGER,
    status VARCHAR(32) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(focus_plan_id, task_id)
);

-- Distraction insights (generated by AI Distraction Detector)
CREATE TABLE IF NOT EXISTS distraction_insights (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    insight_type VARCHAR(64) NOT NULL, -- pattern, trend, recommendation
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    severity VARCHAR(16) DEFAULT 'medium', -- low, medium, high
    time_period_start TIMESTAMP NOT NULL,
    time_period_end TIMESTAMP NOT NULL,
    patterns_detected JSONB DEFAULT '[]'::jsonb,
    recommendations JSONB DEFAULT '[]'::jsonb,
    actions_taken JSONB DEFAULT '[]'::jsonb,
    status VARCHAR(32) DEFAULT 'active', -- active, acknowledged, resolved
    created_at TIMESTAMP DEFAULT NOW(),
    acknowledged_at TIMESTAMP,
    resolved_at TIMESTAMP
);

-- Smart suggestions (AI-generated productivity recommendations)
CREATE TABLE IF NOT EXISTS smart_suggestions (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    suggestion_type VARCHAR(64) NOT NULL, -- schedule_optimization, task_prioritization, break_timing, etc.
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    rationale TEXT, -- Why this suggestion was made
    priority_score DECIMAL(3, 2) DEFAULT 0.0, -- 0.0 to 1.0
    action_items JSONB DEFAULT '[]'::jsonb,
    expected_benefit TEXT,
    context_data JSONB DEFAULT '{}'::jsonb,
    status VARCHAR(32) DEFAULT 'pending', -- pending, accepted, rejected, implemented
    created_at TIMESTAMP DEFAULT NOW(),
    accepted_at TIMESTAMP,
    implemented_at TIMESTAMP,
    feedback_score INTEGER CHECK (feedback_score >= 1 AND feedback_score <= 5),
    feedback_notes TEXT
);

-- User productivity profile (for AI predictions and suggestions)
CREATE TABLE IF NOT EXISTS user_productivity_profiles (
    user_id VARCHAR(64) PRIMARY KEY,
    average_focus_session_minutes DECIMAL(6, 2),
    peak_productivity_hours JSONB DEFAULT '[]'::jsonb, -- Hours when user is most productive
    average_task_duration_minutes DECIMAL(6, 2),
    preferred_focus_duration INTEGER,
    common_distraction_patterns JSONB DEFAULT '[]'::jsonb,
    productivity_trends JSONB DEFAULT '{}'::jsonb,
    ai_model_parameters JSONB DEFAULT '{}'::jsonb,
    last_calculated_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- AI model training data cache
CREATE TABLE IF NOT EXISTS ai_training_cache (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    model_type VARCHAR(64) NOT NULL, -- time_prediction, distraction_detection, etc.
    feature_vector JSONB NOT NULL,
    target_value DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT NOW(),
    used_for_training BOOLEAN DEFAULT FALSE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_user_status ON tasks(user_id, status);
CREATE INDEX IF NOT EXISTS idx_activity_patterns_user_id ON activity_patterns(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_patterns_timestamp ON activity_patterns(timestamp);
CREATE INDEX IF NOT EXISTS idx_activity_patterns_user_time ON activity_patterns(user_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_time_predictions_user_id ON time_predictions(user_id);
CREATE INDEX IF NOT EXISTS idx_time_predictions_task_id ON time_predictions(task_id);
CREATE INDEX IF NOT EXISTS idx_focus_plans_user_id ON focus_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_focus_plans_status ON focus_plans(status);
CREATE INDEX IF NOT EXISTS idx_distraction_insights_user_id ON distraction_insights(user_id);
CREATE INDEX IF NOT EXISTS idx_distraction_insights_status ON distraction_insights(status);
CREATE INDEX IF NOT EXISTS idx_smart_suggestions_user_id ON smart_suggestions(user_id);
CREATE INDEX IF NOT EXISTS idx_smart_suggestions_status ON smart_suggestions(status);
CREATE INDEX IF NOT EXISTS idx_smart_suggestions_type ON smart_suggestions(suggestion_type);

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON tasks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_productivity_profiles_updated_at BEFORE UPDATE ON user_productivity_profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

