/**
 * Summary Service
 * 
 * Generates productivity summaries and statistics for users.
 * Integrates with AI service for enhanced summaries.
 * 
 * @module services/summaryService
 * @deprecated This service is being phased out in favor of analyticsService
 */

const axios = require('axios');
const serverConfig = require('../server.config');
<<<<<<< HEAD
const logger = require('../utils/logger').child('SummaryService');
=======
const logger = require('../utils/logger');

function getPythonServiceBaseUrl() {
  return (serverConfig.integrations.pythonServiceUrl || 'http://localhost:8000').replace(/\/$/, '');
}

async function requestSummaryFromPython({ content, tone = 'concise' }) {
  const baseUrl = getPythonServiceBaseUrl();
  const url = `${baseUrl}/api/summaries`;
  const timeout = Number.parseInt(process.env.SUMMARY_SERVICE_TIMEOUT_MS || '10000', 10);
  const response = await axios.post(
    url,
    { content, tone },
    {
      timeout,
      headers: {
        'Content-Type': 'application/json'
      }
    }
  );
  return response.data;
}
>>>>>>> origin/main

/**
 * Generates placeholder statistics
 * 
 * @deprecated Use analyticsService instead
 * @returns {Promise<Object>} Placeholder statistics object
 * 
 * @example
 * const stats = await generatePlaceholderStats();
 */
async function generatePlaceholderStats() {
<<<<<<< HEAD
  logger.warn('generatePlaceholderStats is deprecated - use analyticsService instead');
  
  // Placeholder implementation - should be replaced with real analytics
  const pythonServiceUrl = serverConfig.integrations.pythonServiceUrl;
  
  try {
    // In the future, this could call the Python AI service for enhanced summaries
    // const response = await axios.get(`${pythonServiceUrl}/api/summaries/stats`);
    // return response.data;
    
    return {
      focusedMinutes: 120,
      distractionsAvoided: 6,
      summaryServiceUrl: pythonServiceUrl,
      note: 'This is a placeholder. Use analyticsService for real statistics.'
    };
  } catch (error) {
    logger.error('Failed to generate placeholder stats', error);
    // Return default stats on error
    return {
      focusedMinutes: 0,
      distractionsAvoided: 0,
      summaryServiceUrl: pythonServiceUrl,
      error: 'Summary service unavailable'
    };
  }
=======
  return {
    focusedMinutes: 120,
    distractionsAvoided: 6,
    summaryServiceUrl: serverConfig.integrations.pythonServiceUrl
  };
>>>>>>> origin/main
}

/**
 * Generates a meeting summary from free-form meeting notes.
 * @param {object} options
 * @param {string} options.userId
 * @param {string} options.transcript
 * @param {number} options.noteCount
 * @param {number} options.windowMinutes
 * @returns {Promise<{summary:string,metadata:object}>}
 */
async function generateMeetingSummary({ userId, transcript, noteCount, windowMinutes }) {
  const trimmedTranscript = (transcript || '').trim();
  const metrics = {
    noteCount: noteCount || 0,
    windowMinutes: windowMinutes || 180
  };

  if (!trimmedTranscript) {
    return {
      summary: 'No meeting notes collected yet.',
      metadata: { ...metrics, skipped: true }
    };
  }

  const content = [
    `Generate a concise meeting summary for ${userId || 'an unknown user'}.`,
    `Time window: last ${metrics.windowMinutes} minutes.`,
    'Meeting notes:',
    trimmedTranscript
  ].join('\n');

  try {
    const response = await requestSummaryFromPython({ content, tone: 'professional' });
    return {
      summary: response?.summary || 'Summary generated by Python service.',
      metadata: {
        ...metrics,
        serviceMetadata: response?.metadata || {},
        provider: 'python_service'
      }
    };
  } catch (error) {
    logger.error('[SummaryService] Meeting summary generation failed; using fallback.', error);
    const fallbackSummary = trimmedTranscript.split('\n').slice(0, 3).join(' ');
    return {
      summary: fallbackSummary || 'Meeting summary unavailable.',
      metadata: {
        ...metrics,
        provider: 'fallback',
        error: error.message
      }
    };
  }
}

module.exports = { generatePlaceholderStats, generateMeetingSummary };
